version: '3'

services: 

  github-release:
    image: 'github-release'
    build: './src/app'

  docker-push:
    image: 'tmvdl/projects:speed'
    build: './src/app'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

