name: GitHub pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: echo github
        run: echo ${{ github.* }}

      - name: echo env
        run: echo ${{ env.* }}

      - name: echo vars
        run: echo ${{ vars.* }}

      - name: echo job
        run: echo ${{ job.* }}

      - name: echo secrets
        run: echo ${{ secrets.* }}

      - name: echo strategy
        run: echo ${{ strategy.* }}

      - name: echo matrix
        run: echo ${{ matrix.* }}

      - name: echo needs
        run: echo ${{ needs.* }}

      - name: echo inputs
        run: echo ${{ inputs.* }}

      # - name: Push www
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh repo clone brtmvdl/brtmvdl.github.io
      #     cd brtmvdl.github.io
      #     cp ${{ github.workspace }}/src/www/ ./sucht -rfv
      #     git add ./sucht
      #     git commit -m "Fixing "
