name: GitHub release

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # - name: Pull subprojects
      #   run: bash env/pull.sh

      - name: Build apk
        run: docker-compose up apk

      - name: Export apk
        run: docker run -v $(pwd)/dist:/dist -w /dist apk cp /app/hello/platforms/android/app/build/outputs/apk/debug/*.apk . 

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

