name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Release build
        run: docker-compose run builder npm install && npm run build

      - name: Docker build Speed
        run: docker-compose build speed

      - name: Docker build github-release
        run: docker-compose build github-release

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist github-release cp -rfv ./platforms/android/app/build/outputs/apk/debug/*.apk /dist 

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
